const characterActionTypes = {
  FETCH_CHARACTER_START: "FETCH_CHARACTER_START",
  FETCH_CHARACTER_SUCCESS: "FETCH_CHARACTER_SUCCESS",
  FETCH_CHARACTER_FAILURE: "FETCH_CHARACTER_FAILURE",
  FETCH_CHARACTERID_START: "FETCH_CHARACTERID_START",
  FETCH_CHARACTERID_SUCCESS: "FETCH_CHARACTERID_SUCCESS",
  FETCH_CHARACTERID_FAILURE: "FETCH_CHARACTERID_FAILURE",
  SEARCH_CHARACTER_START: "SEARCH_CHARACTER_START",
  SEARCH_CHARACTER_SUCCESS: "SEARCH_CHARACTER_SUCCESS",
  SEARCH_CHARACTER_FAILURE: "SEARCH_CHARACTER_FAILURE",
};

export default characterActionTypes;
